; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{87FAAAFF-4EB4-427D-966F-757F56C59807}
AppName=File to PDF Converter
AppVersion=1.0
;AppVerName={cm:NameAndVersion,File to PDF Converter,1.0}
DefaultDirName={autopf}\File to PDF Converter
UninstallDisplayIcon={app}\FileConverterApp.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=Desktop\FileConverterApp_Installer\
OutputBaseFilename=FileConverterApp_Setup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\FileConverterApp.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\Fonts\*"; DestDir: "{app}\Fonts"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\libre\*"; DestDir: "{app}\libre"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\FileConverterApp.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\FileConverterApp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\FileConverterApp.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\FileConverterApp.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Administrator\Desktop\converter\FileConverterApp\bin\Release\net8.0-windows\FileConverterApp.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.
[Icons]
Name: "{autoprograms}\File to PDF Converter"; Filename: "{app}\FileConverterApp.exe"
Name: "{autodesktop}\File to PDF Converter"; Filename: "{app}\FileConverterApp.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\FileConverterApp.exe"; Description: "{cm:LaunchProgram,File to PDF Converter}"; Flags: nowait postinstall skipifsilent

